# FOSSA Configuration
# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md

version: 3

# Omit project name to use auto-detected GitHub URL (matches quick import)

targets:
  only:
    - type: swift
      path: MiddleDrag.xcodeproj/project.xcworkspace/xcshareddata/swiftpm

# Exclude directories that shouldn't be scanned
paths:
  exclude:
    - build/
    - .build/
    - DerivedData/
    - TestResults.xcresult/
